language: go
go:
  - 1.10.1
before_install:
  - go get github.com/stretchr/testify/assert
  - go get -t -v ./...
script:
  - go test -race -coverprofile=coverage.txt github.com/cooldrip/jhop
after_success:
  - bash <(curl -s https://codecov.io/bash)
